name = "Clines"
uuid = "b03ef683-e087-4e84-9649-40693305c655"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.2.2"


[deps]
LinearFractionalTransformations = "8bac944d-a3a1-5789-a62e-204935847c3c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SimpleDrawing = "d78a06e8-ae74-583c-9a07-0d6572347000"

[compat]
LinearFractionalTransformations = "0.1, 0.2"
Plots = "1"
SimpleDrawing = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
